images:
  mps: 046171614672.dkr.ecr.us-west-2.amazonaws.com/c2c-ecr:mps-v2.7.0
  rps: aws_ecr/c2c-rps:2.7
  webui: intel/oact-webui:v2.5.1
  mpsrouter: 046171614672.dkr.ecr.us-west-2.amazonaws.com/c2c-ecr:mpsrouter-v2.1.1
mps:
  commonName: null
  replicaCount: 1
  logLevel: silly
  jwtExpiration: 1440
ui:
  replicaCount: 1
rps:
  replicaCount: 1
  logLevel: silly
vault:
  injector:
    annotations:
      kuma.io/sidecar-injection: disabled
  server:
    annotations:
      kuma.io/sidecar-injection: disabled
  ui:
    annotations:
      kuma.io/sidecar-injection: disabled
    enabled: true
    serviceType: LoadBalancer
kong:
  ingressController:
    admissionWebhook:
      enabled: false
    ingressClass: kong
  podAnnotations:
    kuma.io/sidecar-injection: enabled
    kuma.io/gateway: enabled
  env:
    UPSTREAM_KEEPALIVE_POOL_SIZE: 0
  proxy:
    stream:
      - containerPort: 4433
        servicePort: 4433
        parameters: []
mpsrouter:
  replicaCount: 1
