name: "rps"

on:
  push:
    branches:
      - [main, test]
  pull_request:
    types: 
      - closed
      - edited
      - synchronize
      - opened
    branches:
      - [main, test]
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RPS_TAG: ''
  ECR_URL: 046171614672.dkr.ecr.us-west-2.amazonaws.com

jobs:

  checkout-repo:
    name: Checkout repo
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Change rps helm values
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: './values.yaml'
          propertyPath: 'images.rps'
          value: aws_ecr/c2c-rps:2.7
          commitChange: true
          message: "ci(rps): updating to version 2.7"
          createPR: true
          title: "ci(rps): updating to version 2.7"
          description: "Automatic PR generated by pipeline"
          branch: ${{github.event.pull_request.head.ref}}
          targetBranch: main
          masterBranchName: main
